// Team member data — update with real info
export interface TeamMember {
  id: number;
  nameEn: string;
  nameFa: string;
  roleEn: string;
  roleFa: string;
  email: string;
  phone: string;
  bioEn: string;
  bioFa: string;
  avatar: string; // initials for avatar
  color: string;  // bg color for avatar
  image?: string; // path to image file
  type?: "team" | "pastor"; // distinguish pastors from team members
}

export const teamMembers: TeamMember[] = [
  {
    id: 1,
    nameEn: "Ali",
    nameFa: "علی",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "ع",
    color: "bg-blue-600",
    image: "/Ali.jpg",
    type: "team",
  },
  {
    id: 2,
    nameEn: "Mehran",
    nameFa: "مهران",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "م",
    color: "bg-purple-600",
    image: "/mehran.jpg",
    type: "team",
  },
  {
    id: 3,
    nameEn: "Alireza",
    nameFa: "علیرضا",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "ع‌ر",
    color: "bg-green-600",
    image: "/Alireza.jpg",
    type: "team",
  },
  {
    id: 4,
    nameEn: "Maryam",
    nameFa: "مریم",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "م‌م",
    color: "bg-rose-600",
    image: "/maryam.jpg",
    type: "team",
  },
  {
    id: 5,
    nameEn: "Ahmad",
    nameFa: "احمد",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "احـ",
    color: "bg-orange-600",
    image: "/Ahmad.jpg",
    type: "team",
  },
  {
    id: 6,
    nameEn: "Sara",
    nameFa: "سارا",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "س",
    color: "bg-teal-600",
    image: "/Sara.jpg",
    type: "team",
  },
  {
    id: 7,
    nameEn: "Matin",
    nameFa: "متین",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "مت",
    color: "bg-indigo-600",
    image: "/Matin.webp",
    type: "team",
  },
  {
    id: 8,
    nameEn: "Farshid",
    nameFa: "فرشید",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "ف",
    color: "bg-amber-600",
    image: "/Farshid.jpg",
    type: "team",
  },
  {
    id: 10,
    nameEn: "Roohangiz",
    nameFa: "روهنگیز",
    roleEn: "Team Member",
    roleFa: "عضو تیم",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Dedicated servant of the Abe Hayaat retreat team.",
    bioFa: "خادم متعهد تیم ریتریت آب حیات.",
    avatar: "ر",
    color: "bg-fuchsia-600",
    image: "/Roohangiz.jpg",
    type: "team",
  },
  {
    id: 11,
    nameEn: "Pastor Daniel",
    nameFa: "پاستور دانیل",
    roleEn: "Lead Pastor",
    roleFa: "پاستور رهبر",
    email: "parvizianfarshid@gmail.com",
    phone: "+49 17650971",
    bioEn: "Lead pastor of Abe Hayaat Church.",
    bioFa: "پاستور رهبر کلیسای آب حیات.",
    avatar: "د",
    color: "bg-red-600",
    image: "/Pastor.Daniel.jpg",
    type: "pastor",
  },
];

export const churchInfo = {
  nameEn: "Abe Hayaat Church",
  nameFa: "کلیسای آب حیات",
  address: "Germany",
  addressFa: "آلمان",
  phone: "+49 17650971",
  email: "parvizianfarshid@gmail.com",
  website: "abehayat.vercel.app",
};
